# Generated by Django 4.1.7 on 2023-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_news1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='news1',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
