# Generated by Django 4.1.7 on 2023-03-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_delete_news_alter_news1_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
